server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://172.16.11.153:3306/stock_master?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: IamWild!@#123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.16.11.153
    port: 6379
    timeout: 1000
    database: 0

logging:
  file:
    name: /logs/stock-service.log
  level:
    root: info
    org.springfromework.web: info
    org.springframework.jdbc: debug
